### PR TITLE
Added i2c for outputs / inputs

### PR DESCRIPTION
**Pull request by kondrez**

### CODE REVIEW

**Comment by wouterdebruijn** [comment]
I have merged the new c++ modules classes with this code, this creates a nice boilerplate for the creation of new modules. We just need to clean up the Wemos code a bit to make it match with the project code syntax and style.

**Comment by wouterdebruijn** [comment]
I have formatted the files for better readability. Should be ready to change around some of the methods / variable names next. Might be able to safe some RAM by using constants where possible.

**Comment by wouterdebruijn** [comment]
As this repository now contains build actions, it might be a good idea to make an new repository for the wemos module codebase.

**Review by wouterdebruijn — APPROVED** [review]
LGTM!

**Comment by Casper-Bastiaan-Net** [comment]
looks good to me.

**Pull request merged**
